/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tcp;

import java.awt.event.KeyEvent;

/**
 *
 * @author 834398
 */
public class ClienteForm extends javax.swing.JFrame {

    private final Cliente con;
    
    
    public ClienteForm() {
        initComponents();
        
        txtVelha1.setEditable(false);
        txtVelha2.setEditable(false);
        txtVelha3.setEditable(false);
        txtVelha4.setEditable(false);
        txtVelha5.setEditable(false);
        txtVelha6.setEditable(false);
        txtVelha7.setEditable(false);
        txtVelha8.setEditable(false);
        txtVelha9.setEditable(false);
        
        this.setTitle("Cliente TCP");
        this.setResizable(false);
        con = new Cliente(txtHistorico,txtVelha1,txtVelha2,txtVelha3,txtVelha4,txtVelha5,txtVelha6,txtVelha7,txtVelha8,txtVelha9);
        con.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtVelha1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHistorico = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txtVelha7 = new javax.swing.JTextField();
        txtVelha4 = new javax.swing.JTextField();
        txtVelha8 = new javax.swing.JTextField();
        txtVelha2 = new javax.swing.JTextField();
        txtVelha5 = new javax.swing.JTextField();
        txtVelha9 = new javax.swing.JTextField();
        txtVelha3 = new javax.swing.JTextField();
        txtVelha6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtVelha1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtVelha1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtVelha1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtVelha1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Jogo da Velha - Cliente");

        txtHistorico.setColumns(20);
        txtHistorico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtHistorico.setRows(5);
        jScrollPane1.setViewportView(txtHistorico);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Historico");

        txtVelha7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtVelha7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtVelha7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtVelha7MouseClicked(evt);
            }
        });

        txtVelha4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtVelha4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtVelha4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtVelha4MouseClicked(evt);
            }
        });

        txtVelha8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtVelha8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtVelha8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtVelha8MouseClicked(evt);
            }
        });

        txtVelha2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtVelha2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtVelha2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtVelha2MouseClicked(evt);
            }
        });

        txtVelha5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtVelha5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtVelha5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtVelha5MouseClicked(evt);
            }
        });

        txtVelha9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtVelha9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtVelha9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtVelha9MouseClicked(evt);
            }
        });

        txtVelha3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtVelha3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtVelha3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtVelha3MouseClicked(evt);
            }
        });

        txtVelha6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtVelha6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtVelha6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtVelha6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVelha1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtVelha4)
                                .addComponent(txtVelha7, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVelha2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVelha5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVelha8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtVelha3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVelha6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVelha9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVelha1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVelha2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVelha3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVelha4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVelha5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVelha6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVelha7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVelha8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVelha9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtVelha1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtVelha1MouseClicked
        // TODO add your handling code here:
        txtVelha1.setText("O");
        Mensagem msg = new Mensagem(
                txtVelha1.getText(), txtVelha2.getText(),
                txtVelha3.getText(), txtVelha4.getText(),
                txtVelha5.getText(), txtVelha6.getText(),
                txtVelha7.getText(), txtVelha8.getText(),
                txtVelha9.getText()
            );
            
            con.enviar(msg);
            
            txtVelha1.setText("O");
    }//GEN-LAST:event_txtVelha1MouseClicked

    private void txtVelha2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtVelha2MouseClicked
        // TODO add your handling code here:
        txtVelha2.setText("O");
        Mensagem msg = new Mensagem(
                txtVelha1.getText(), txtVelha2.getText(),
                txtVelha3.getText(), txtVelha4.getText(),
                txtVelha5.getText(), txtVelha6.getText(),
                txtVelha7.getText(), txtVelha8.getText(),
                txtVelha9.getText()
            );
            
            con.enviar(msg);
            
            txtVelha2.setText("O");
    }//GEN-LAST:event_txtVelha2MouseClicked

    private void txtVelha3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtVelha3MouseClicked
        // TODO add your handling code here:
        txtVelha3.setText("O");
        Mensagem msg = new Mensagem(
                txtVelha1.getText(), txtVelha2.getText(),
                txtVelha3.getText(), txtVelha4.getText(),
                txtVelha5.getText(), txtVelha6.getText(),
                txtVelha7.getText(), txtVelha8.getText(),
                txtVelha9.getText()
            );
            
            con.enviar(msg);
            
            txtVelha3.setText("O");
    }//GEN-LAST:event_txtVelha3MouseClicked

    private void txtVelha4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtVelha4MouseClicked
        // TODO add your handling code here:
        txtVelha4.setText("O");
        Mensagem msg = new Mensagem(
                txtVelha1.getText(), txtVelha2.getText(),
                txtVelha3.getText(), txtVelha4.getText(),
                txtVelha5.getText(), txtVelha6.getText(),
                txtVelha7.getText(), txtVelha8.getText(),
                txtVelha9.getText()
            );
            
            con.enviar(msg);
            
            txtVelha4.setText("O");
    }//GEN-LAST:event_txtVelha4MouseClicked

    private void txtVelha5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtVelha5MouseClicked
        // TODO add your handling code here:
        txtVelha5.setText("O");
        Mensagem msg = new Mensagem(
                txtVelha1.getText(), txtVelha2.getText(),
                txtVelha3.getText(), txtVelha4.getText(),
                txtVelha5.getText(), txtVelha6.getText(),
                txtVelha7.getText(), txtVelha8.getText(),
                txtVelha9.getText()
            );
            
            con.enviar(msg);
            
            txtVelha5.setText("O");
    }//GEN-LAST:event_txtVelha5MouseClicked

    private void txtVelha6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtVelha6MouseClicked
        // TODO add your handling code here:
        txtVelha6.setText("O");
        Mensagem msg = new Mensagem(
                txtVelha1.getText(), txtVelha2.getText(),
                txtVelha3.getText(), txtVelha4.getText(),
                txtVelha5.getText(), txtVelha6.getText(),
                txtVelha7.getText(), txtVelha8.getText(),
                txtVelha9.getText()
            );
            
            con.enviar(msg);
            
            txtVelha6.setText("O");
    }//GEN-LAST:event_txtVelha6MouseClicked

    private void txtVelha7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtVelha7MouseClicked
        // TODO add your handling code here:
        txtVelha7.setText("O");
        Mensagem msg = new Mensagem(
                txtVelha1.getText(), txtVelha2.getText(),
                txtVelha3.getText(), txtVelha4.getText(),
                txtVelha5.getText(), txtVelha6.getText(),
                txtVelha7.getText(), txtVelha8.getText(),
                txtVelha9.getText()
            );
            
            con.enviar(msg);
            
            txtVelha7.setText("O");
    }//GEN-LAST:event_txtVelha7MouseClicked

    private void txtVelha8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtVelha8MouseClicked
        // TODO add your handling code here:
        txtVelha8.setText("O");
        Mensagem msg = new Mensagem(
                txtVelha1.getText(), txtVelha2.getText(),
                txtVelha3.getText(), txtVelha4.getText(),
                txtVelha5.getText(), txtVelha6.getText(),
                txtVelha7.getText(), txtVelha8.getText(),
                txtVelha9.getText()
            );
            
            con.enviar(msg);
            
            txtVelha8.setText("O");
    }//GEN-LAST:event_txtVelha8MouseClicked

    private void txtVelha9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtVelha9MouseClicked
        // TODO add your handling code here:
        txtVelha9.setText("O");
        Mensagem msg = new Mensagem(
                txtVelha1.getText(), txtVelha2.getText(),
                txtVelha3.getText(), txtVelha4.getText(),
                txtVelha5.getText(), txtVelha6.getText(),
                txtVelha7.getText(), txtVelha8.getText(),
                txtVelha9.getText()
            );
            
            con.enviar(msg);
            
            txtVelha9.setText("O");
    }//GEN-LAST:event_txtVelha9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtHistorico;
    private javax.swing.JTextField txtVelha1;
    private javax.swing.JTextField txtVelha2;
    private javax.swing.JTextField txtVelha3;
    private javax.swing.JTextField txtVelha4;
    private javax.swing.JTextField txtVelha5;
    private javax.swing.JTextField txtVelha6;
    private javax.swing.JTextField txtVelha7;
    private javax.swing.JTextField txtVelha8;
    private javax.swing.JTextField txtVelha9;
    // End of variables declaration//GEN-END:variables
}
